name: datosenv2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - adwaita-icon-theme=48.0
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - anyio=4.10.0
  - aom=3.12.1
  - arrow-cpp=21.0.0
  - async-timeout=5.0.1
  - at-spi2-atk=2.34.2
  - at-spi2-core=2.36.0
  - atk-1.0=2.36.0
  - attrs=25.4.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - beautifulsoup4=4.14.2
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.2.0.0
  - bs4=4.14.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - datasets=4.4.1
  - dav1d=1.2.1
  - dbus=1.16.2
  - dill=0.4.0
  - epoxy=1.5.4
  - exceptiongroup=1.3.0
  - expat=2.7.3
  - filelock=3.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.61.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.8.0
  - gdk-pixbuf=2.42.10
  - gensim=4.4.0
  - gettext=0.21.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.84.4
  - glib-tools=2.84.4
  - glog=0.5.0
  - gobject-introspection=1.84.0
  - graphite2=1.3.14
  - graphviz=12.2.1
  - gtk3=3.24.21
  - gts=0.7.6
  - h11=0.16.0
  - harfbuzz=10.2.0
  - hf-xet=1.1.8
  - hicolor-icon-theme=0.17
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.34.4
  - icu=73.1
  - idna=3.11
  - intel-openmp=2025.0.0
  - jansson=2.14
  - joblib=1.5.2
  - jpeg=9f
  - kiwisolver=1.4.9
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.3.0
  - libboost=1.88.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcups=2.4.15
  - libcurl=8.16.0
  - libdeflate=1.22
  - libdrm=2.4.124
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgd=2.3.3
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.4
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgrpc=1.71.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libidn2=2.3.8
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libnghttp2=1.67.1
  - libnsl=2.0.0
  - libopengl=1.7.0
  - libopenjpeg=2.5.4
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - librsvg=2.56.3
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libtool=2.4.7
  - libunistring=1.3
  - libuuid=1.41.5
  - libuv=1.48.0
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - mesalib=25.1.5
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - multidict=6.7.0
  - multiprocess=0.70.18
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - ncurses=6.5
  - ninja=1.13.1
  - ninja-base=1.13.1
  - nltk=3.9.2
  - nspr=4.37
  - nss=3.117
  - numexpr=2.14.1
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.0
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - pango=1.50.7
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - poppler=24.09.0
  - poppler-data=0.4.12
  - propcache=0.4.1
  - protobuf=5.29.3
  - pthread-stubs=0.3
  - pyarrow=21.0.0
  - pycares=4.10.0
  - pycparser=2.23
  - pyparsing=3.2.5
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-graphviz=0.21
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.3
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwayland=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - re2=2024.07.02
  - readline=8.3
  - regex=2025.11.3
  - requests=2.32.5
  - s2n=1.5.14
  - safetensors=0.6.2
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - seaborn=0.13.2
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - smart_open=7.3.1
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - spirv-tools=2025.1
  - sqlite=3.51.0
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - tokenizers=0.21.0
  - tomli=2.2.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - transformers=4.49.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.1
  - utf8proc=2.6.1
  - uvloop=0.22.1
  - wayland=1.24.0
  - wheel=0.45.1
  - wrapt=2.0.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.22.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.12.0
      - fsspec==2025.12.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - psutil==7.1.3
      - sympy==1.14.0
      - torch==2.9.1
      - triton==3.5.1
prefix: /home/hugo/miniconda3/envs/datosenv2
